apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  podTemplate:
    annotations:
        ad.datadoghq.com/kafka.check_names: '["kafka"]'
        ad.datadoghq.com/kafka.init_configs: '[{"is_jmx": true, "collect_default_metrics": true}]'
        ad.datadoghq.com/kafka.instances: '[{"host": "%%host%%","port":"7203"}]'
        ad.datadoghq.com/kafka.logs: '[{"source":"kafka","service":"kafka"}]'
  tls:
    secretRef: tls-group1
  listeners:
    external:
      externalAccess:
        staticForHostBasedRouting:
          domain: my.domain.commmm # <--- example modification
