apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: confluent-portworx-sc
parameters:
  repl: "2"
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
