apiVersion: v1
kind: Namespace
metadata:
  name: confluent-prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prod-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: confluent-infra
  interval: 5m
  path: ./kustomize/environments/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
