apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: default
spec:
  url: https://kubernetes.github.io/ingress-nginx
  interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        name: ingress-nginx
        kind: HelmRepository
        namespace: default
  upgrade:
    timeout: 30s
    remediation:
      retries: 3
      strategy: rollback
    cleanupOnFail: true
  rollback:
    timeout: 1m
    force: true
    cleanupOnFail: true
  values:
    controller.extraArgs.enable-ssl-passthrough: true
