apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
spec:
  replicas: 2
  storageClass:
    name: confluent-portworx-sc  
  image:
    application: confluentinc/cp-ksqldb-server:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  dataVolumeCapacity: 10Gi
