apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
spec:
  podTemplate:
    probe:
      liveness:
        periodSeconds: 10
        failureThreshold: 1
        timeoutSeconds: 5 
