apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: testadmin-rb-sr
spec:
  principal:
    type: user
    name: testadmin
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_sandbox
  role: SystemAdmin
